/*Problem 45 - Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/


package main

import "fmt"

func main() {

    nTri := 287;
    nPent := 165;

    for {

        triVal := tri( nTri );
        pentVal := pent( nPent );

    	if triVal > pentVal {
    		nPent++;
    	} else if triVal < pentVal {
    		nTri += 2; //we add by two because every second triangle is a hexagon value, so we don't have to hex() ever.
    		nPent--;
    	} else if triVal == pentVal {
    		fmt.Printf( "Found: %v at triangle index %v\n", triVal, nTri );
    		break;
    	} else {
    		fmt.Printf( "Spooky Error at triangle index %v\n", nTri );
    		break;
    	}
    }

}


func tri(n int)int {
	return n * ( n + 1 ) / 2;
}

func pent(n int)int {
	return n * ( ( 3 * n ) - 1 ) / 2;
}

func hex(n int)int {
	return n * ( ( 2 * n ) - 1 );
}
